---
title: "Lab 02"
output: pdf_document
---

```{r}
library(RSQLite)
library(DBI)
dbcon = dbConnect(SQLite(), dbname="C:/Users/John/Desktop/STAT 240/Data/lab02.sqlite")
```

Question 1a \
The column names of  the data table `zip':
```{r}
names(dbReadTable(dbcon, "zip"))
```




Question 1b \
The last 5 records in the data table `CA':
```{r}
tail(dbReadTable(dbcon, "CA"), n=5)
```

Question 1c \
The last 3 records of the data table `POP2011':
```{r}
tail(dbReadTable(dbcon, "POP2011"), n=3)
```

Question 1d \
```{r}
nrow(dbReadTable(dbcon, "POP2006")) #check row numbers
```
There are 1624 records in the data table 'POP2006'

\newpage
Question 2a
```{r}
sql_qry = "SELECT city, state, zip_code FROM zip WHERE state = 'IL'"
nrow(dbGetQuery(dbcon, sql_qry))
```
1596 Records are returned by this query.

\newpage
Question 3a
```{r}
sql_qry = "SELECT * FROM zip INNER JOIN tickets ON zip.zip_code=tickets.zip_code 
WHERE fine_level1_amount > 100"
d=dbGetQuery(dbcon, sql_qry)
sum(d$latitude,na.rm=TRUE)
```
The sum of the latitudes is 2709141.

\newpage
Question 4a
```{r}
library(sp)
library(rworldmap)
library(rworldxtra)
worldmap = getMap(resolution = "high")
NrthAm = worldmap[which(worldmap$REGION=="North America"),]
plot(NrthAm,  main="Canadian locations with population less than 16278", col="white", bg="lightblue",
     xlim=c(-140,-55), ylim=c(42,72), )

qrt = "SELECT Latitude, Longitude FROM CA INNER JOIN POP2006 ON CA.Geographic_name == POP2006.Geographic_name
WHERE POP2006.Population__2006 < 16278"
p=dbGetQuery(dbcon,qrt)
points(x=p$Longitude, y=p$Latitude, col="red", pch=16)
```




